# Generated by Django 5.1.1 on 2024-09-21 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_cart_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='subtotal',
        ),
    ]
