# Generated by Django 5.1 on 2024-10-04 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestemail',
            old_name='activate',
            new_name='active',
        ),
    ]
