# Generated by Django 5.1.1 on 2024-09-15 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_remove_cart_subtotal'),
        ('orders', '0003_order_active_order_billing_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='carts.cart'),
        ),
    ]
