# Generated by Django 5.1 on 2025-02-15 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('billing', 'Billing'), ('shipping', 'Shipping')], max_length=120)),
                ('endereço_1', models.CharField(max_length=120)),
                ('endereço_2', models.CharField(blank=True, max_length=120, null=True)),
                ('cidade', models.CharField(max_length=120)),
                ('país', models.CharField(default='Brazil', max_length=120)),
                ('estado', models.CharField(max_length=120)),
                ('cep', models.CharField(max_length=120)),
                ('billing_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.billingprofile')),
            ],
        ),
    ]
