# Generated by Django 5.1 on 2024-10-31 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='postal_code',
            new_name='cep',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='city',
            new_name='cidade',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address_line_1',
            new_name='endereço_1',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address_line_2',
            new_name='endereço_2',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='state',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='country',
            new_name='país',
        ),
    ]
